#!/usr/bin/env bash
# Builds /etc/agentforge.env from SSM Parameter Store.
#
# Run by the systemd unit's ExecStartPre, so the app never reads SSM itself
# and no secret is committed, baked into an AMI, or captured in a snapshot.
# Requires an instance role with ssm:GetParameters + kms:Decrypt.
set -euo pipefail

REGION="${AWS_REGION:-ap-south-1}"
PREFIX="/agentforge"
OUT="/etc/agentforge.env"

# Secrets — fetched decrypted from SSM.
SECRETS=(
  GEMINI_API_KEY
  GROQ_API_KEY
  OPENROUTER_API_KEY
  REDIS_URL
  GOOGLE_CLIENT_ID
  GOOGLE_CLIENT_SECRET
  GOOGLE_REDIRECT_URI
  CLIENT_ORIGIN
)

TMP="$(mktemp)"
chmod 600 "$TMP"

{
  echo "# Generated by agentforge-load-env at $(date -u +%FT%TZ). Do not edit."
  echo "NODE_ENV=production"
  echo "PORT=4000"
  # 7 days. A 1-hour TTL meant a user idle over lunch had to re-consent.
  # Google's own refresh tokens do not expire while the app's publishing
  # status is In production, so this Redis TTL is the only ceiling.
  echo "SESSION_TTL_SECONDS=604800"
  echo "SANDBOX_IMAGE=agentforge-sandbox:local"
  echo "GEMINI_MODEL=gemini-3.5-flash-lite"
  echo "GROQ_MODEL=openai/gpt-oss-120b"
  echo "OPENROUTER_MODEL=nvidia/nemotron-3-super-120b-a12b:free"
} > "$TMP"

for name in "${SECRETS[@]}"; do
  value="$(aws ssm get-parameter \
    --region "$REGION" \
    --name "${PREFIX}/${name}" \
    --with-decryption \
    --query 'Parameter.Value' \
    --output text 2>/dev/null || true)"

  if [ -z "$value" ] || [ "$value" = "None" ]; then
    # GOOGLE_CLIENT_SECRET is in the list above because this server talks to
    # the Gmail API itself and needs it to refresh an expired access token.
    echo "WARNING: ${PREFIX}/${name} not set in SSM — skipping" >&2
    continue
  fi
  printf '%s=%s\n' "$name" "$value" >> "$TMP"
done

install -m 600 -o root -g root "$TMP" "$OUT"
rm -f "$TMP"
echo "Wrote $OUT"
